//
//  MockData.swift
//  Recipe App
//
//  Created by Marco Alonso Rodriguez on 17/01/24.
//

import Foundation

struct MockData {
    static let recipes = [
        RecipeModel(owner: "Marco Alonso", dishPicture: "https://www.recetasnestle.com.mx/sites/default/files/srh_recipes/f395e167c1613770edb2b32d44260c80.jpg", ownerPicture: "https://depor.com/resizer/iKuIRVVSoS2-EZT-szBYuDAQQ60=/1200x1200/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/INQGMHTMCVDSNFMGVWFPRKKFOI.jpg", isFavourite: false, dishName: "Hot Cakes", descriptionPreparation: "Mezcla 1.  Mezcla la Leche Evaporada CARNATION® CLAVEL® con el huevo, 2 cucharadas de mantequilla fundida, la esencia de vainilla y la harina para hot cakes. Calienta 2.  Calienta una sartén, agrega un poco de mantequilla y con ayuda de un cucharón vierte un poco de la mezcla para formar los hot cakes; cocina por ambos lados y repite el procedimiento con el resto de la preparación. Consejo culinario 3.  Sirve los hot cakes, decora con moras azules, fresas, las hojas de menta y con un poco de Leche Condensada LA LECHERA® Sirve Fácil. Ofrece.", minutesPreparation: 30),
        RecipeModel(owner: "Wilibaldo Tapia", dishPicture: "https://i.ytimg.com/vi/kZjMv5dkRUw/maxresdefault.jpg", ownerPicture: "https://images.ecestaticos.com/--zy4X01BUBN8SpSedp65AwEdg4=/265x4:2272x1510/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F705%2F241%2F828%2F705241828aaea0f2fbaabff881e582d7.jpg", isFavourite: false, dishName: "Carne Apache", descriptionPreparation: "Mezcla 1.  Mezcla la Leche Evaporada CARNATION® CLAVEL® con el huevo, 2 cucharadas de mantequilla fundida, la esencia de vainilla y la harina para hot cakes. Calienta 2.  Calienta una sartén, agrega un poco de mantequilla y con ayuda de un cucharón vierte un poco de la mezcla para formar los hot cakes; cocina por ambos lados y repite el procedimiento con el resto de la preparación. Consejo culinario 3.  Sirve los hot cakes, decora con moras azules, fresas, las hojas de menta y con un poco de Leche Condensada LA LECHERA® Sirve Fácil. Ofrece.", minutesPreparation: 30),
        RecipeModel(owner: "Lizeth Loeza", dishPicture: "https://assets.unileversolutions.com/recipes-v2/232561.jpg", ownerPicture: "https://media.glamour.mx/photos/61c6045d486fbc658c9f184a/master/pass/MargotRobbiesombrasplata.jpeg", isFavourite: false, dishName: "Lassagna", descriptionPreparation: "Mezcla 1.  Mezcla la Leche Evaporada CARNATION® CLAVEL® con el huevo, 2 cucharadas de mantequilla fundida, la esencia de vainilla y la harina para hot cakes. Calienta 2.  Calienta una sartén, agrega un poco de mantequilla y con ayuda de un cucharón vierte un poco de la mezcla para formar los hot cakes; cocina por ambos lados y repite el procedimiento con el resto de la preparación. Consejo culinario 3.  Sirve los hot cakes, decora con moras azules, fresas, las hojas de menta y con un poco de Leche Condensada LA LECHERA® Sirve Fácil. Ofrece.", minutesPreparation: 30),
        RecipeModel(owner: "Santiago Loeza", dishPicture: "https://www.flancasero.com/wp-content/uploads/2020/01/flan-napolitano.jpg", ownerPicture: "https://imagenes.20minutos.es/files/image_1920_1080/uploads/imagenes/2022/04/27/andrew-garfield.jpeg", isFavourite: false, dishName: "Flan", descriptionPreparation: "Mezcla 1.  Mezcla la Leche Evaporada CARNATION® CLAVEL® con el huevo, 2 cucharadas de mantequilla fundida, la esencia de vainilla y la harina para hot cakes. Calienta 2.  Calienta una sartén, agrega un poco de mantequilla y con ayuda de un cucharón vierte un poco de la mezcla para formar los hot cakes; cocina por ambos lados y repite el procedimiento con el resto de la preparación. Consejo culinario 3.  Sirve los hot cakes, decora con moras azules, fresas, las hojas de menta y con un poco de Leche Condensada LA LECHERA® Sirve Fácil. Ofrece.", minutesPreparation: 30)
    ]
}
